apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: shipping-api-upstream
  namespace: default
spec:
  endpoints:
    - fqdn:
        hostname: partner-api.example.com
        port: 443
