apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: reporting-gateway
  namespace: reporting
spec:
  gatewayClassName: eg
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
