apiVersion: v1
kind: Service
metadata:
  name: crm-api-legacy
  namespace: crm-api
spec:
  selector:
    app: crm-api-legacy
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: crm-api-next
  namespace: crm-api
spec:
  selector:
    app: crm-api-next
  ports:
    - port: 8080
      targetPort: 8080
